[package]
name = "website_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
askama = "0.12"
askama_warp = "0.12"
serde = { version = "1.0", features = ["derive"] }